rm(list = ls(all.names = TRUE))

library(tidyverse)
library(readxl)
library(lubridate)

Engineering_Metrics_Jul19 <- read_excel("~/R/R Data/S&OP/Engineering_Metrics_Jul19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "text"), skip = 41)
Engineering_Metrics_Aug19 <- read_excel("~/R/R Data/S&OP/Engineering_Metrics_Aug19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "text"), skip = 41)
Engineering_Metrics_Sep19 <- read_excel("~/R/R Data/S&OP/Engineering_Metrics_Sep19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "text"), skip = 41)
Engineering_Metrics_Oct19 <- read_excel("~/R/R Data/S&OP/Engineering_Metrics_Oct19.xlsx", 
                                        sheet = "Compass Order Summary", col_types = c("text", 
                                                                                       "numeric", "text", "text", "text", 
                                                                                       "text", "date", "numeric", "numeric", 
                                                                                       "text", "text", "text", "text", "text", 
                                                                                       "text", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "numeric", "numeric", "numeric", 
                                                                                       "numeric", "text", "numeric", "numeric", 
                                                                                       "numeric", "numeric", "text", "numeric", 
                                                                                       "numeric", "numeric", "numeric", 
                                                                                       "text", "text"), skip = 41)



combined_order_summary <- bind_rows("'JUL-19" = Engineering_Metrics_Jul19,
                                    "'AUG-19" = Engineering_Metrics_Aug19,
                                    "'SEP-19" = Engineering_Metrics_Sep19,
                                    "'OCT-19" = Engineering_Metrics_Oct19,
                                    .id = "Period")
write.csv(combined_order_summary, "~/R/R Data/S&OP/combined_order_summary.csv")